"""Replaceable face-analysis components for tracked people."""

from .base import (
    BBox,
    FaceAligner,
    FaceCrop,
    FaceCropper,
    FaceDetection,
    FaceDetector,
    FaceDetectorError,
    FaceLandmark5,
    FaceLandmarker,
    FaceQualityDecision,
    FaceQualityEvaluator,
    FaceQualityReason,
    FaceQualityResult,
    NoOpFaceAligner,
    crop_frame,
)
from .fake import FakeFaceDetector
from .factory import (
    create_face_detector,
    create_face_embedder,
    create_face_landmarker,
    create_face_matcher,
    create_face_orchestrator,
)
from .onnx import DisabledFaceDetector, OnnxFaceDetector
from .detectors import (
    OpenVINOFaceDetector0205,
    OpenVINOLandmarksRegressor,
    OpenVino0205FaceDetector,
    ScrfdFaceDetector,
    YuNetFaceDetector,
)
from .openvino import OpenVINOFaceEmbedder
from .alignment import (
    AlignmentTemplate,
    ARC_FACE_TEMPLATE,
    FACENET_TEMPLATE,
    RETAIL_0095_TEMPLATE,
    FaceAlignmentError,
    SimilarityFaceAligner,
)
from .capabilities import FaceCapability, face_capability_matrix, validate_capability
from .model_resolution import (
    FaceModelResolution,
    FaceModelResolutionError,
    model_format,
    normalize_device_for_backend,
    resolve_detector,
    resolve_recognizer,
)
from .registry import (
    FACE_DETECTOR_SPECS,
    LANDMARKER_SPEC,
    RECOGNIZER_SPECS,
    artifact_sha256,
)
from .embedding import (
    EmbeddingModelMetadata,
    FaceEmbedder,
    FaceEmbeddingError,
    FakeEmbedder,
    IncompatibleEmbeddingModelError,
    OnnxFaceEmbedder,
)
from .enrollment import (
    EnrollmentError,
    EnrollmentBatchPersonReport,
    EnrollmentBatchReport,
    EnrollmentBatchService,
    EnrollmentImageResult,
    EnrollmentReport,
    EnrollmentService,
    SUPPORTED_IMAGE_SUFFIXES,
)
from .storage import (
    PersonAlreadyExistsError,
    PersonRecord,
    PersonStorageError,
    PersonStore,
    person_id_from_name,
)
from .service import FaceAnalysisResult, FaceAnalysisService, TrackedFaceResult
from .orchestrator import FaceOrchestrationResult, FaceRecognitionOrchestrator
from .matcher import FaceMatcher, FaceMatcherError, RecognitionResult, RecognitionStatus
from .confirmation import RecognitionConfirmation, TrackRecognitionConfirmer
from .calibration import (
    CalibrationError,
    CalibrationReport,
    CalibrationSample,
    ScoreDistribution,
    ThresholdEvaluation,
    calibrate_scores,
    evaluate_threshold,
    read_score_samples,
)

__all__ = [
    "BBox",
    "FaceAligner",
    "FaceAnalysisResult",
    "FaceAnalysisService",
    "FaceOrchestrationResult",
    "FaceRecognitionOrchestrator",
    "FaceCrop",
    "FaceCropper",
    "FaceDetection",
    "FaceDetector",
    "FaceDetectorError",
    "FaceLandmark5",
    "FaceLandmarker",
    "FaceQualityDecision",
    "FaceQualityEvaluator",
    "FaceQualityReason",
    "FaceQualityResult",
    "FakeFaceDetector",
    "FakeEmbedder",
    "DisabledFaceDetector",
    "EmbeddingModelMetadata",
    "EnrollmentError",
    "EnrollmentBatchPersonReport",
    "EnrollmentBatchReport",
    "EnrollmentBatchService",
    "EnrollmentImageResult",
    "EnrollmentReport",
    "EnrollmentService",
    "FaceEmbedder",
    "FaceEmbeddingError",
    "FaceMatcher",
    "FaceMatcherError",
    "IncompatibleEmbeddingModelError",
    "NoOpFaceAligner",
    "OnnxFaceDetector",
    "OnnxFaceEmbedder",
    "OpenVINOFaceDetector0205",
    "OpenVINOLandmarksRegressor",
    "OpenVino0205FaceDetector",
    "OpenVINOFaceEmbedder",
    "ScrfdFaceDetector",
    "YuNetFaceDetector",
    "AlignmentTemplate",
    "ARC_FACE_TEMPLATE",
    "FACENET_TEMPLATE",
    "RETAIL_0095_TEMPLATE",
    "FaceAlignmentError",
    "SimilarityFaceAligner",
    "FaceCapability",
    "FaceModelResolution",
    "FaceModelResolutionError",
    "face_capability_matrix",
    "validate_capability",
    "model_format",
    "normalize_device_for_backend",
    "resolve_detector",
    "resolve_recognizer",
    "FACE_DETECTOR_SPECS",
    "LANDMARKER_SPEC",
    "RECOGNIZER_SPECS",
    "artifact_sha256",
    "PersonAlreadyExistsError",
    "PersonRecord",
    "PersonStorageError",
    "PersonStore",
    "RecognitionConfirmation",
    "RecognitionResult",
    "RecognitionStatus",
    "SUPPORTED_IMAGE_SUFFIXES",
    "TrackedFaceResult",
    "TrackRecognitionConfirmer",
    "CalibrationError",
    "CalibrationReport",
    "CalibrationSample",
    "ScoreDistribution",
    "ThresholdEvaluation",
    "calibrate_scores",
    "evaluate_threshold",
    "read_score_samples",
    "create_face_detector",
    "create_face_embedder",
    "create_face_landmarker",
    "create_face_matcher",
    "create_face_orchestrator",
    "crop_frame",
    "person_id_from_name",
]
